### ISSUE TITLE
Use gdisk for Windows to create bootloader partitions

### ISSUE THREAD

**Issue by Googulator** [SuperJMN/Lumia950XL-WOA-Scripts#4]
A build of gdisk is available for Windows at https://osdn.net/projects/sfnet_gptfdisk/downloads/gptfdisk/1.0.1/gdisk-binaries/gdisk-windows-1.0.1.zip/

This can be used to create the 2 bootloader partitions which we currently require Linux for.

**Comment by SuperJMN** [comment]
Fortunately, this is no longer needed!
